n_symbols: 32
symbols_embedding_dim: 32
encoder_kernel_size: 5
encoder_n_convolutions: 2
encoder_embedding_dim: 32
attention_rnn_dim: 32
decoder_rnn_dim: 32
attention_dim: 16
attention_location_n_filters: 8
attention_location_kernel_size: 15
prenet_dim: 16
max_decoder_steps: 50
gate_threshold: 0.5
p_attention_dropout: 0.1
p_decoder_dropout: 0.1
postnet_embedding_dim: 32
postnet_kernel_size: 5
postnet_n_convolutions: 3
n_mels: 16
